### PR TITLE
Fixes for Julia 1.0

### PR DESCRIPTION
**Pull request by odow**
I ran into some 32-bit Windows failures while working on https://github.com/JuliaOpt/MathOptInterface.jl/pull/969. 

Here's the Appveyor log:
https://ci.appveyor.com/project/JuliaOpt/mathoptinterface-jl/builds/29419127/job/kruunajq0kw66gk1

I'm going to spend some time tidying up this package. 

This PR:

 - Adds a Project.toml
 - Simplifies the travis and appveyor submission scripts
 - Switches the tests from the master branch of the test-suite to a tag because they're working on a new draft

### CODE REVIEW

**Comment by odow** [comment]
That's weird. For some reason Travis isn't showing up in Github, even though it ran here:
https://travis-ci.org/fredo-dedup/JSONSchema.jl/builds/622841635

@fredo-dedup any ideas?

At least we can re-produce this 32-bit failure.

**Comment by odow** [comment]
Bump @fredo-dedup

**Comment by fredo-dedup** [comment]
Thanks Oscar, I will try to take look in the coming days.....

Le mer. 18 déc. 2019 à 16:25, Oscar Dowson <notifications@github.com> a
écrit :

**Comment by odow** [comment]
> I will try to take look in the coming days...

Thanks! This change is pretty small, but since this package is now pretty important to my work (and will be installed for everyone who uses JuMP), I'm going put in some time tidying up the code.

If you don't see yourself having the time for reviews, would you consider adding me as a collaborator?

**Comment by fredo-dedup** [comment]
Merged.
I have added you as a collaborator too. 
Tell me if you still have any remaining issue after that.

**Pull request merged**
