### PR TITLE
Relax type signatures for `Dict` -> `AbstractDict` 

### PR DESCRIPTION
**Pull request by yongheekim-dev**
fix for https://github.com/fredo-dedup/JSONSchema.jl/issues/19

And would it make sense to treat `Missing` as `null` too? because JSON.jl does this. https://github.com/JuliaIO/JSON.jl/pull/257

### CODE REVIEW

**Comment by odow** [comment]
Can we relax the type signatures throughout `schema.jl` and `validation.jl` as well?

> would it make sense to treat Missing as null too?

Yes. But let's do this as a separate pull request. It would need a test as well.

**Comment by yongheekim-dev** [comment]
Got it. I've reverted that commit

**Comment by odow** [comment]
What about relaxing signatures such as https://github.com/fredo-dedup/JSONSchema.jl/blob/7ab003186685b5f32dce7945bd0484467e4adb23/src/validation.jl#L64 
https://github.com/fredo-dedup/JSONSchema.jl/blob/7ab003186685b5f32dce7945bd0484467e4adb23/src/validation.jl#L150

There are lots of other ones.

**Comment by yongheekim-dev** [comment]
Yeah you are light. 

https://github.com/yongheekim-dev/JSONSchema.jl/blob/67c30c37bc08ec0977bec22782c8a6750659c850/src/schema.jl#L149-L150 
But I wasn't sure how to handle `Dict{String, Any}`

This is not working. 
```julia
julia> function foo(id_map::T{String, Any}) where T <: AbstractDict
       end
ERROR: TypeError: in Type{...} expression, expected UnionAll, got TypeVar
```

**Comment by odow** [comment]
For others reading, I think it's okay that the `data` field of `Schema` is `::AbstractDict` because we use a function barrier:
https://github.com/fredo-dedup/JSONSchema.jl/blob/7ab003186685b5f32dce7945bd0484467e4adb23/src/validation.jl#L53-L54

**Pull request merged**
